### ISSUE TITLE
压缩包损坏

### ISSUE THREAD

**Issue by BlackTravel** [HsinTsao/SwissKnife#1]
SwiffKnife 压缩包损坏

**Comment by HsinTsao** [comment]
放假中，将会在2.6日检修这个问题

**Comment by HsinTsao** [comment]
> SwiffKnife 压缩包损坏

检查发现，可能是由于项目太大（63M+），并且github连接不稳定，导致以zip方式下载容易失败。我已经删除多余的debug文件，现在项目只有1.75M（代码+资源）。可以尝试再次下载，或者借助码云clone本仓库。

**Comment by BlackTravel** [comment]
感谢您的负责和付出 ，我会认真阅读您的代码。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月7日(星期一) 下午3:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HsinTsao/SwissKnife] 压缩包损坏 (Issue #1)





  
SwiffKnife 压缩包损坏
  
检查发现，可能是由于项目太大（63M+），并且github连接不稳定，导致以zip方式下载容易失败。我已经删除多余的debug文件，现在项目只有1.75M（代码+资源）。可以尝试再次下载，或者借助码云clone本仓库。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
